[package]
name = "bevy_rapier3d_f64"
version = "0.33.0"
authors = ["Sébastien Crozet <developer@crozet.re>"]
description = "3-dimensional physics engine in Rust, official Bevy plugin (double-precision Rapier)."
documentation = "http://docs.rs/bevy_rapier3d"
homepage = "http://rapier.rs"
repository = "https://github.com/dimforge/bevy_rapier"
readme = "../README.md"
keywords = ["physics", "dynamics", "rigid", "real-time", "joints"]
license = "Apache-2.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "../src/lib.rs"
required-features = ["dim3", "f64"]

[lints]
rust.unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(feature, values("dim2", "f32", "f64"))',
] }
clippy = { needless_lifetimes = "allow" }

[features]
default = [
    "dim3",
    "f64",
    "async-collider",
    "debug-render-3d",
    "picking-backend",
    "to-bevy-mesh",
]
dim3 = []
f64 = []
debug-render = ["debug-render-3d"]
debug-render-2d = [
    "bevy/bevy_core_pipeline",
    "bevy/bevy_sprite",
    "bevy/bevy_gizmos",
    "rapier3d-f64/debug-render",
    "bevy/bevy_asset",
]
debug-render-3d = [
    "bevy/bevy_core_pipeline",
    "bevy/bevy_pbr",
    "bevy/bevy_gizmos",
    "rapier3d-f64/debug-render",
    "bevy/bevy_asset",
]
rapier-debug-render = ["rapier3d-f64/debug-render"]

parallel = ["rapier3d-f64/parallel"]
simd-stable = ["rapier3d-f64/simd-stable"]
simd-nightly = ["rapier3d-f64/simd-nightly"]
serde-serialize = ["rapier3d-f64/serde-serialize", "bevy/serialize", "serde"]
enhanced-determinism = ["rapier3d-f64/enhanced-determinism"]
headless = []
picking-backend = ["bevy/bevy_picking", "bevy/bevy_render"]
async-collider = [
    "bevy/bevy_asset",
    "bevy/bevy_scene",
    "bevy/bevy_render",
    "bevy/bevy_image",
]
to-bevy-mesh = ["bevy/bevy_render", "bevy/bevy_asset"]

[dependencies]
bevy = { version = "0.18.0", default-features = false, features = ["std"] }
nalgebra = { version = "0.34.1", features = ["convert-glam030"] }
rapier3d-f64 = "0.31.0"
bitflags = "2.10.0"
log = "0.4"
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
bevy = { version = "0.18.0", default-features = false, features = [
    "bevy_window",
    "x11",
    "tonemapping_luts",
    "bevy_state",
    "bevy_debug_stepping",
    "bevy_text",
    "bevy_ui",
    "default_font",
    "bevy_log",
    "bevy_gizmos_render",
] }
approx = "0.5.1"
glam = { version = "0.30.9", features = ["approx"] }
bevy-inspector-egui = "0.36.0"
bevy_egui = "0.39.0"
bevy_mod_debugdump = "0.15.0"

[package.metadata.docs.rs]
features = ["debug-render-3d", "serde-serialize", "async-collider"]

[package.metadata.cargo-all-features]

denylist = ["simd-nightly"]

skip_feature_sets = [["enhanced-determinism", "simd-stable"]]

always_include_features = ["dim3"]

max_combination_size = 1
